### PR TITLE
Needed ISS live location with Google map

### PR DESCRIPTION
**Pull request by meerhamzadev**
Hey 👋, I implement the Iive location with google maps. Actually, before opening the pull request,  I didn't saw the upstream, that's why my request is 2 commits behind. Hope you don't find any difficulty. 

The screenshots of implementations are: 
Screenshot 2021-10-02 at 23-25-04 Space Voyager

Screenshot 2021-10-02 at 23-25-32 Space Voyager

Untitled

And in the IssMap.js file, you are supposed to provide your API key. Hope you easily get it, If you find any problem with getting the API key, feel free to contact ✌.

image

-- And don't forget to add the **Hacktoberfest** label :) --

### CODE REVIEW

**Comment by mohittk** [comment]
> Hey 👋, I implement the Iive location with google maps. Actually, before opening the pull request, I didn't saw the upstream, that's why my request is 2 commits behind. Hope you don't find any difficulty.
> 
> The screenshots of implementations are: Screenshot 2021-10-02 at 23-25-04 Space Voyager
> 
> Screenshot 2021-10-02 at 23-25-32 Space Voyager
> 
> Untitled
> 
> And in the IssMap.js file, you are supposed to provide your API key. Hope you easily get it, If you find any problem with getting the API key, feel free to contact ✌.
> 
> image
> 
> -- And don't forget to add the **Hacktoberfest** label :) --

Great work! Hope it's working well.
There are some conflicts for merging it into master.
I'll solve them tomorrow and merge them,
Or you can also try to resolve the conflicting files !

**Comment by meerhamzadev** [comment]
Actually I'm going to sleep and I am able to resolve it tomorrow 😅. You are good to go.

**Comment by mohittk** [comment]
> Actually I'm going to sleep and I am able to resolve it tomorrow 😅. You are good to go.

Yea! It's my sleeping time too.!
That's why I postponed for it later on.

**Comment by mohittk** [comment]
@MeerHamza1421  Bro please join discord server, so that we can communicate properly. these files have, conflicts because you did'nt fetched upstream.

**Pull request closed without merging**
