### PR TITLE
Implement auto suggestion in satellite search

### LINKED ISSUE #34: Needed autosuggestion in search-bar for satellite page.
While entering query in search bar, there should be pane displaying autosuggestion for names of satellites.

### PR DESCRIPTION
**Pull request by PaulKovalov**
Implement satellite search autosuggestion by querying input on change.

Couldn't find any version reference to update, according to the contribution guidelines. Please point me at them if there are any.

Closes space-voyager-21/space-voyager#34

### CODE REVIEW

**Comment by mohittk** [comment]
> Implement satellite search autosuggestion by querying input on change.
> 
> Couldn't find any version reference to update, according to the contribution guidelines. Please point me at them if there are any.
> 
> Closes #34

Great work dude! Had you fetched upstream before commit? just check and confirm it to me once.

**Comment by PaulKovalov** [comment]
Just merged master into it

**Comment by mohittk** [comment]
> Just merged master into it

you made it ! Thankyou.

**Comment by PaulKovalov** [comment]
Thank you!

**Comment by abh80** [comment]
Nice ❤

**Pull request merged**
