### PR TITLE
Optimized fetch query code with additional submit button.

### PR DESCRIPTION
**Pull request by chaitanyks**
Optimized the fetch query approach, No need to check keypress data every time.

### CODE REVIEW

**Review by mohittk — CHANGES_REQUESTED** [review]
Well done bro!
Are you familiar with CSS? 
If yes, Please add approporiate CSS to submit button according to the theme.

**Comment by chaitanyks** [comment]
CSS is kind of hard for me, I am very bad at designing.

**Comment by mohittk** [comment]
> CSS is kind of hard for me, I am very bad at designing.

Umm.. okaay! No problem.

**Review by mohittk — APPROVED** [review]

**Comment by umgbhalla** [comment]
@gaurav147-star could help with css

**Comment by gaurav147-star** [comment]
@umgbhalla ya sure ..

**Comment by mohittk** [comment]
> 

@gaurav147-star Have you started working upon it? Actually I already did with "submit" button css in my local, so if you have'nt started, I can commit.

**Comment by gaurav147-star** [comment]
@mohittk ya,you can commit

**Comment by mohittk** [comment]
> @mohittk ya,you can commit

Sure! Looking for more contributions from you @gaurav147-star

**Pull request merged**
