### PR TITLE
(JS-0125) Found the usage of undeclared variables #22

### PR DESCRIPTION
**Pull request by ramdevcm**

### CODE REVIEW

**Comment by mohittk** [comment]
@ramdevcm are you sure, this things solves the issues? Like you just changed these things.
image

**Comment by ramdevcm** [comment]
image

**Comment by mohittk** [comment]
Okay! cool work.

**Comment by mohittk** [comment]
closes #42

**Comment by mohittk** [comment]
closes #22

**Comment by ramdevcm** [comment]
Is this not accepted as #hacktoberfest lol

**Pull request merged**
