### PR TITLE
Needed ISS live location with Google map [updated]

### PR DESCRIPTION
**Pull request by meerhamzadev**
Hey @mohittk 👋, Sorry for the bit late reply. I closed the previous pull request and after resolving all conflicts. I'm raising a new request, hope it wouldn't make any problem now. And kindly share the discord link, so I can connect with awesome devs 🙌.

### CODE REVIEW

**Comment by mohittk** [comment]
@MeerHamza1421 Have you fetched upstream this time? 
Discord link : https://discord.gg/FpEK9AqbCf

**Comment by meerhamzadev** [comment]
Yes, I fetched upstream first this time and then implement it. There are no merge conflicts now.

**Comment by mohittk** [comment]
> Yes, I fetched upstream first this time and then implement it. There are no merge conflicts now.

The deploy failed again bro. Need to fix.

**Comment by umgbhalla** [comment]
image

**Comment by meerhamzadev** [comment]
> 
> 
> > Yes, I fetched upstream first this time and then implement it. There are no merge conflicts now.
> 
> The deploy failed again bro. Need to fix.

why 👀

**Comment by meerhamzadev** [comment]
It might be due to the missing of API key

**Comment by meerhamzadev** [comment]
@umgbhalla I resolved that issue.

**Comment by umgbhalla** [comment]
> @umgbhalla I resolved that issue.

yep 
looks good for merge ? @mohittk

**Comment by meerhamzadev** [comment]
Hey @mohittk, I update the API.

**Comment by mohittk** [comment]
@MeerHamza1421 The page is working now but! this issue is right there.
image
have a look.

**Comment by meerhamzadev** [comment]
Yes it's due to the unavailability of the google maps API key when you add API key it removed. If you view the console, the error of API key would be shown

**Comment by mohittk** [comment]
> Yes it's due to the unavailability of the google maps API key when you add API key it removed. If you view the console, the error of API key would be shown

Okay! So what's next for this? Any solution?

**Comment by meerhamzadev** [comment]
https://developers.google.com/maps/documentation/javascript/cloud-setup

Go to this URL. It contains each and every detail of how to get a Google Map API key. First, you create a project on the google cloud platform and so on. To ensure the smooth working of the map don't forget to configure a billing account.

**Pull request merged**
