### PR TITLE
landingpage css changes and also make this responsive

### LINKED ISSUE #30: CSS needed to be updated with proper flex. on landing page
image

@gaurav147-star Have a look, I'll assign it to you.

### PR DESCRIPTION
**Pull request by gaurav147-star**
image
image

@mohittk check this ...if anything to improve suggest me
#30

### CODE REVIEW

**Comment by gaurav147-star** [comment]
@umgbhalla u can also check this

**Comment by mohittk** [comment]
> image image
> 
> @mohittk check this ...if anything to improve suggest me

Well done! dude.
One change suggestion , like can you just make all blocks of same size
Like it does'nt matter no. of words in that blocks. They should remain of same size.

**Comment by mohittk** [comment]
> image image
> 
> @mohittk check this ...if anything to improve suggest me

Well! Its allright. I am satisfied.

**Comment by mohittk** [comment]
@gaurav147-star  edit and mention the issue you solved.

**Review by umgbhalla — APPROVED** [review]

**Pull request merged**
